name: 'Pull request tests'

on:
  # Run after build completes, will need to filter out release builds
  workflow_run:
    workflows: ['Build PRs and main']
    types:
    - completed

jobs:
  test:
    name: 'Test pull request'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      if: ${{ github.ref_name != 'main' && github.event.workflow_run.conclusion == 'success' }}
      uses: actions/checkout@v2.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Create artifact dir
      if: ${{ github.ref_name != 'main' && github.event.workflow_run.conclusion == 'success' }}
      run: |
        mkdir -p /tmp/artifacts

    - name: Download PR artifacts
      if: ${{ github.ref_name != 'main' && github.event.workflow_run.conclusion == 'success' }}
      uses: dawidd6/action-download-artifact@v2.16.0
      with:
        workflow: build.yaml
        name: test-dist-${GITHUB_SHA}
        path: /tmp/artifacts
        search_artifacts: true
        check_artifacts: true

    - name: Dummy test
      # Don't run tests after main builds
      if: ${{ github.ref_name != 'main' && github.event.workflow_run.conclusion == 'success' }}
      run: |
        echo "There are no tests yet. Good Luck :)"
        ls -lah /tmp/artifacts
